# Файл локализации для игры.
# Здесь хранится перевод и описание всех игровых объектов и их характеристик.

AlmanacScreen.name=Альманах
AlmanacScreen.zombies=Зомби
AlmanacScreen.plants=Растения
AlmanacScreenZombie.name=Альманах - зомби
AlmanacScreenPlants.name=Альманах - растения

SettingScreen.name=Настройки
SettingScreen.isFullscreen.on=Полный экран
SettingScreen.isFullscreen.off=Окно
SettingScreen.isAutoSunSelectionEnabled=Автоподбор Солнца: Вкл
SettingScreen.isAutoSunSelectionDisabled=Автоподбор Солнца: Выкл

button.back=Назад

Level.plantselect=Выберите ваши растения
Level.start=Вперед!
Level.almanac=Альманах
Level.button.menu=Меню
level.zombies=Зомби
level.text.start1=на старт...
level.text.start2=внимание...
level.text.start3=САЖАЙ!
level.text.zombiewave=ПРИБЛИЖАЕТСЯ ОГРОМНАЯ ВОЛНА ЗОМБИ!
level.text.zombiewavefinal=ФИНАЛЬНАЯ ВОЛНА

#Имена уровней
level.name.test=Тестовый Уровень - Зомби

entity.hp=Хп
entity.damage=Урон

# Зомби
zombie.name=Зомби
zombie.types=Обычный садовый зомби.
zombie.desc=Простой зомби, который медленно идет к тебе с жаждой вкусных мозгов. Не представляет серьезной угрозы, но в большом количестве может быть опасен.